### ISSUE TITLE
Navigation?

### ISSUE THREAD

**Issue by ESTAVEX** [lazareric/StarterPack#1]
How is navigation handled? It doesn't work on mobile and the styles are reset to default on desktop. Update the docs on how to set up the navigation. Also, favicon is missing in the project, it ouputs errors in the console every time you click on a link.

**Comment by lazareric** [comment]
That's the thing. This is not Bootstrap, it's an alternative for full custom projects, so you have to build all those specific parts yourself, this is only a setup. Favicon, as well, they are all linked in head, which you can delete some, leave one, whatever, or for each size of favicon, add your own (to the img/favicon folder) so you wouldn't get an error...
